# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '30 20 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Looks like this issue has not been updated in 14 days. Is it still needed?'
        stale-pr-message: 'Looks like this PR has not been updated in 14 days. Is it still needed?'
        days-before-stale: 60
        close-issue-message: 'Looks like this stale issue has not been updated in 7 days. Closing the issue.'
        close-pr-message: 'Looks like this stale PR has not been updated in 7 days. Closing the PR.'
        days-before-close: 7
